apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcd-app
  labels:
    app: pcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pcd-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: pcd-app-container
          image: tmp # check image
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /live
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
